// DO NOT MODIFY -- GENERATED BY buildIndex.js
exports.abis = {};
exports.abis["AaveKandel"] = require("./dist/abis/AaveKandel.json");
exports.abis["AaveKandelSeeder"] = require("./dist/abis/AaveKandelSeeder.json");
exports.abis[
  "AbstractKandelSeeder"
] = require("./dist/abis/AbstractKandelSeeder.json");
exports.abis["AbstractRouter"] = require("./dist/abis/AbstractRouter.json");
exports.abis["AccessControlled"] = require("./dist/abis/AccessControlled.json");
exports.abis["GeometricKandel"] = require("./dist/abis/GeometricKandel.json");
exports.abis[
  "ICreditDelegationToken"
] = require("./dist/abis/ICreditDelegationToken.json");
exports.abis[
  "ILiquidityProvider"
] = require("./dist/abis/ILiquidityProvider.json");
exports.abis["IOfferLogic"] = require("./dist/abis/IOfferLogic.json");
exports.abis["Kandel"] = require("./dist/abis/Kandel.json");
exports.abis["KandelSeeder"] = require("./dist/abis/KandelSeeder.json");
exports.abis["MangroveOrder"] = require("./dist/abis/MangroveOrder.json");
exports.abis["OfferMaker"] = require("./dist/abis/OfferMaker.json");
exports.addresses = {};
exports.addresses.deployed = {};
exports.addresses.deployed[
  "arbitrum"
] = require("./addresses/deployed/arbitrum.json");
exports.addresses.deployed[
  "matic"
] = require("./addresses/deployed/matic.json");
exports.addresses.deployed[
  "maticmum"
] = require("./addresses/deployed/maticmum.json");
exports.addresses.context = {};
exports.addresses.context[
  "arbitrum"
] = require("./addresses/context/arbitrum.json");
exports.addresses.context[
  "goerli"
] = require("./addresses/context/goerli.json");
exports.addresses.context["matic"] = require("./addresses/context/matic.json");
exports.addresses.context[
  "maticmum"
] = require("./addresses/context/maticmum.json");
