# Note: remember to `git submodule update --recursive` to pull in dependencies
[profile.default]
src='packages/mangrove-solidity/src'
broadcast='packages/mangrove-solidity/broadcast'
script='packages/mangrove-solidity/script'
test='packages/mangrove-solidity/test'
out='packages/mangrove-solidity/out'
libs=['packages/mangrove-solidity/lib']
cache_path='packages/mangrove-solidity/cache'
fs_permissions = [{ access = "read-write", path = "./packages/mangrove-solidity/addresses/"}]
solc_version="0.8.14"
# optimizer=true
# optimizer_runs=20000

# Private keys are expected to be of the form <NETWORK>_PRIVATE_KEY
# The relevant code is in Deployer.sol
[rpc_endpoints]
polygon="${POLYGON_NODE_URL}"
mumbai="${MUMBAI_NODE_URL}"
[etherscan]
mumbai={key="${POLYGON_API_KEY}"}

# The remappings are in remappings.txt so vscode solidity ext. can read them
# The first lines are the manual remappings
# The other lines are a copy/paste of the inferred mappings shown by `forge config` (inferred from imported libs)
# You should update remappings.txt whenever a lib change impacts remappings
[fmt]
tab_width=2
int_types="short"
number_underscores="thousands"