[profile.default]
src = 'src'
out = 'out'
# libs = ["/Users/kejlberg/Mangrove/mangrove-bots-deploy/node_modules", "lib"]
libs = ["../../node_modules", "lib"]
remappings = ['@uniswap/=../../node_modules/@uniswap/']
fs_permissions = [{ access = "read-write", path = "./addresses/"}, { access = "read", path = "./out/" }]
solc_version="0.8.17"
auto_detect_remappings = false
# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
polygon="${POLYGON_NODE_URL}"
mumbai="${MUMBAI_NODE_URL}"

[etherscan]
goerli={key="${GOERLI_API_KEY}"}
mumbai={key="${POLYGON_API_KEY}"}
polygon={key="${POLYGON_API_KEY}"}
testnet_zkevm={key="${ZKEVM_API_KEY}",chain=1442,url="https://api-testnet-zkevm.polygonscan.com/api"}
zkevm={key="${ZKEVM_API_KEY}",chain=1101,url="https://api-zkevm.polygonscan.com/api"}

[fmt]
tab_width=2
int_types="short"
number_underscores="thousands"