// DO NOT MODIFY -- GENERATED BY buildIndex.js
exports.MgvArbitrage = {};
exports.MgvArbitrage[
  "MgvArbitrage"
] = require("./out/MgvArbitrage.sol/MgvArbitrage.json");
exports.addresses.deployed = {};
exports.addresses.deployed["empty"] = require("./addresses/deployed/empty.js");
