// .prettier-ignore
// DO NOT MODIFY -- GENERATED BY buildIndex.js
exports.MgvArbitrage = {};
exports.MgvArbitrage['MgvArbitrage'] = require("./out/MgvArbitrage.sol/MgvArbitrage.json");
exports.MgvArbitrageForTest = {};
exports.MgvArbitrageForTest['MgvArbitrageForTest'] = require("./out/MgvArbitrageForTest.sol/MgvArbitrageForTest.json");
exports.addresses.deployed = {};
exports.addresses.deployed['matic'] = require("./addresses/deployed/matic.json");