/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MgvArbitrage } from "./MgvArbitrage";
export * as factories from "./factories";
export { MgvArbitrage__factory } from "./factories/MgvArbitrage__factory";
