sources:
  - name: Mangrove
    handler:
      graphql:
        endpoint: https://mangrove-api-proxy-466fefe29e0a.herokuapp.com/mangrove-subgraph/v0.0.6-analytics-4/{context.chainName:matic}
    transforms:
      - autoPagination:
        validateSchema: true

additionalTypeDefs: |
  extend type Market {
    chainName: String!
  }
  extend type Account {
    chainName: String!
  }
  extend type Order {
    chainName: String!
  }
  extend type LimitOrder {
    chainName: String!
  }
  extend type Offer {
    chainName: String!
  }
  extend type AccountVolumeByPair {
    chainName: String!
  }

additionalResolvers:
  - ./src/resolvers.js

documents:
  - src/queries/*.graphql

codegen:
  contextType: "MeshContext & { chainName: string }"
