name: Setup Foundry
description: Install Foundry, load RPC cache, load compilation cache
runs:
  using: composite
  steps:
  - name: Install Foundry
    uses: foundry-rs/foundry-toolchain@v1
    with:
      version: nightly

  - name: Get Foundry RPC cache
    uses: actions/cache@v3
    with:
      path: "~/.foundry/cache"
      key: foundry-rpc-cache-${{ hashFiles('foundry.toml',format('{0}/test/',env.working-directory)) }}
      restore-keys: |
        foundry-rpc-cache-

  - name: Get Foundry build cache
    uses: actions/cache@v3
    with:
      path: |
        ${{ format('{0}/cache',env.working-directory) }}
        ${{ format('{0}/out', env.working-directory) }}
      key: foundry-build-cache-${{ hashFiles('foundry.toml',format('${0}/[lib,script,src,test]/',env.working-directory)) }}
      restore-keys: |
        foundry-build-cache-
    