// DO NOT MODIFY -- GENERATED BY buildIndex.js
exports.abis = {};
exports.abis["IERC20"] = require("./dist/abis/IERC20.json");
exports.abis["IMangrove"] = require("./dist/abis/IMangrove.json");
exports.abis["Mangrove"] = require("./dist/abis/Mangrove.json");
exports.abis["MgvOracle"] = require("./dist/abis/MgvOracle.json");
exports.abis["MgvReader"] = require("./dist/abis/MgvReader.json");
exports.abis["SimpleTestMaker"] = require("./dist/abis/SimpleTestMaker.json");
exports.abis["TestToken"] = require("./dist/abis/TestToken.json");
exports.addresses = {};
exports.addresses.deployed = {};
exports.addresses.deployed[
  "arbitrum"
] = require("./addresses/deployed/arbitrum.json");
exports.addresses.deployed[
  "matic"
] = require("./addresses/deployed/matic.json");
exports.addresses.deployed[
  "maticmum"
] = require("./addresses/deployed/maticmum.json");
exports.addresses.context = {};
exports.addresses.context[
  "arbitrum"
] = require("./addresses/context/arbitrum.json");
exports.addresses.context[
  "goerli"
] = require("./addresses/context/goerli.json");
exports.addresses.context["matic"] = require("./addresses/context/matic.json");
exports.addresses.context[
  "maticmum"
] = require("./addresses/context/maticmum.json");
