name: Test Results
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
jobs:
  test-results:
    name: Test Results
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      continue-on-error: true
      if: ${{ always() }}
      with:
        artifact: test-results-bot-utils
        name: Bot Utils - Tests
        path: '*.json'
        reporter: mocha-json
        fail-on-error: 'false'
    - uses: dorny/test-reporter@v1
      continue-on-error: true
      if: ${{ always() }}
      with:
        artifact: test-results-bot-cleaning
        name: Cleaning Bot - Tests
        path: '*.json'
        reporter: mocha-json
        fail-on-error: 'false'
    - uses: dorny/test-reporter@v1
      continue-on-error: true
      if: ${{ always() }}
      with:
        artifact: test-results-bot-updategas
        name: Update Gas Bot - Tests
        path: '*.json'
        reporter: mocha-json
        fail-on-error: 'false'
    - uses: dorny/test-reporter@v1
      continue-on-error: true
      if: ${{ always() }}
      with:
        artifact: test-results-bot-maker-noise
        name: Noise Maker Bot - Tests
        path: '*.json'
        reporter: mocha-json
        fail-on-error: 'false'
    - uses: dorny/test-reporter@v1
      continue-on-error: true
      if: ${{ always() }}
      with:
        artifact: test-results-bot-taker-greedy
        name: Greedy Taker Bot - Tests
        path: '*.json'
        reporter: mocha-json
        fail-on-error: 'false'
    - uses: dorny/test-reporter@v1
      continue-on-error: true
      if: ${{ always() }}
      with:
        artifact: test-results-bot-failing-offer
        name: Failing Offer Bot - Tests
        path: '*.json'
        reporter: mocha-json
        fail-on-error: 'false'
    - uses: dorny/test-reporter@v1
      continue-on-error: true
      if: ${{ always() }}
      with:
        artifact: test-results-bot-arbitrage
        name: Arbitrage Bot - Tests 
        path: '*.json'
        reporter: mocha-json
        fail-on-error: 'false'
