name: doc

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]
    branches: [master]
    types:
      - completed

jobs:
  publish-mangrove-js-docs:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Download mangrove.js doc artefact from CI run
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}      
        workflow: node.js.yml
        workflow_conclusion: success
        branch: master
        event: push
        name: mangrove-js-documentation
        path: docs/mangrove-js

    - name: Deploy to GitHub Pages branch
      if: success()
      uses: crazy-max/ghaction-github-pages@v3
      with:
        target_branch: gh-pages
        build_dir: docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
