name: Publish Package to npmjs
on:
  release:
    types: [released]
jobs:
  publish_mangrove.js:
    runs-on: ubuntu-latest
    env:
      working-directory: packages/mangrove.js
    defaults:
      run:
        working-directory: ${{env.working-directory}}
    permissions:
      checks: write

    steps:
    # == Git checkout ==
    - name: Checkout
      uses: actions/checkout@v3
      # Workaround for https://github.com/npm/cli/issues/2610
      with:
        persist-credentials: false
        ref: ${{ env.GIT_REF_TO_TEST }}
        submodules: recursive
    - name: Reconfigure git to use HTTP authentication
      # Workaround for https://github.com/npm/cli/issues/2610    
      run: >
        git config --global url."https://github.com/".insteadOf
        ssh://git@github.com/
    - name: Yarn setup (caching yarn dependencies)
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        
    - run: yarn install --immutable
      working-directory: . # Yarn must run in root to ensure monorepo setup

    - name: mangrove.js - Build
      run: yarn run build-this-package

    - name: mangrove.js - Publish
      run: npm publish --access public
      working-directory: packages/mangrove.js
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}


